// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrienyobtvzgqepeioib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyaWVueW9idHZ6Z3FlcGVpb2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzY2NzEsImV4cCI6MjA2NTU1MjY3MX0.q7mvJYsBd4cVy6ww_lb4O_-lGeZj6OJmCCVfBhx8Gng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);